### ISSUE TITLE
Stronger typing

### ISSUE THREAD

**Issue by rudolfbyker** [coldfix/pydicti#6]
I have not yet looked into how to achieve this, but it would be nice if `dicti` was somehow understood by Mypy to be a real subtype of `Dict`. Currently, with strict Mypy settings, it's regarded as `Any`:

```py
def foo() -> Dict[str, str]:
    return dicti({"a": "b"})
```

![image](https://user-images.githubusercontent.com/10025342/207538911-6bd30049-f9be-48c0-afa0-c159a87ac9ac.png)

**Comment by rudolfbyker** [comment]
A good first step would be to [add the py.typed marker](https://dev.to/whtsky/don-t-forget-py-typed-for-your-typed-python-package-2aa3), and ensure that all function arguments and return values have types. The project could benefit from Mypy linting itself, but that is not required.

**Comment by coldfix** [comment]
Thanks! Good point. Unfortunately, I have almost no experience with the typing extensions and mypy, but I can include `py.typed` and possibly look into whether proper definitions are easy to do.

**Comment by rudolfbyker** [comment]
I suspect that creating classes at runtime as this package does will not be compatible with static typing, but it's worth a try.

This is a deal breaker for me, so if we can't figure this out, I might have to jump ship and use something else :)

**Comment by coldfix** [comment]
I don't think it should be that problematic. As a starting point I could add something like `build_dicti: Type[Dict] -> Type[Dict]`, and later think about how to capture the subclass structure properly.

**Comment by coldfix** [comment]
Anyway, maybe you can help me here: how do I easily test type hints (at least manually) once I get started on implementing them.

**Comment by rudolfbyker** [comment]
When you talk about "testing type hints", I can take this to mean one of two things:

1. Type-checking this package to find errors.
2. Testing how types from exported members of this package behave when used in other code.

For both of these, I would simply install mypy, and start by running it with default settings (an empty mypy.ini file). Then you can gradually make it stricter (starting with [`disallow_untyped_defs = true`](https://mypy.readthedocs.io/en/stable/config_file.html#confval-disallow_untyped_defs)).

On the comand line, to check the current folder:

```
mypy .
```

For point 2 above, it's as simple as running `mypy` on some test code like in my original post above.

I hope this answers the question. If not, please rephrase! :)

**Comment by coldfix** [comment]
Thanks!

I've created a PR, see #7. I haven't added checks for case 2 yet. I might simply use the stuff in `test/*.py` for that, but those are a bit messy and fail with multiple internal problems for mypy, partly because of the compatibility code. So this might take some more effort to get it going.

Can you check whether the type hints in #7 work for you?

**Comment by coldfix** [comment]
(Thanks! I meant both case 1 and case 2 and also possibly check whether IDE behaves "as expected")

**Comment by rudolfbyker** [comment]
Regarding the IDE: I use the official Mypy plugin for IntelliJ IDEA. I don't use VSCode much, but there should also be a plugin. It just relays the info from the CLI mypy to the GUI.

**Comment by coldfix** [comment]
New version on PyPI.
